{% set name = "pandas-market-calendars" %}
{% set version = "3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pandas_market_calendars-{{ version }}.tar.gz
  sha256: d7c8130df56b4628c582bcb924c0c5fe664e6ac401f364296481c0bb6daf77e9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - exchange-calendars >=3.3
    - pandas >=1.1
    - python >=3.7
    - python-dateutil
    - pytz

test:
  imports:
    - pandas_market_calendars

about:
  home: https://github.com/rsheftel/pandas_market_calendars
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Market calendars to use with pandas for trading applications.
  description: |
    The Pandas package is widely used in finance and specifically for time
    series analysis. It includes excellent functionality for generating
    sequences of dates and capabilities for custom holiday calendars, but as
    an explicit design choice it does not include the actual holiday calendars
    for specific exchanges or OTC markets.

    The pandas_market_calendars package looks to fill that role with the
    holiday, late open and early close calendars for specific exchanges and
    OTC conventions. pandas_market_calendars also adds several functions to
    manipulate the market calendars and includes a date_range function to
    create a pandas DatetimeIndex including only the datetimes when the
    markets are open.

    This package is a fork of the Zipline package from Quantopian and extracts
    just the relevant parts. All credit for their excellent work to Quantopian.
  doc_url: https://pandas-market-calendars.readthedocs.io/en/latest/
  dev_url: https://github.com/rsheftel/pandas_market_calendars

extra:
  recipe-maintainers:
    - timkpaine
    - mathiaseitz
    - trendelkampschroer
    - yehoshuadimarsky
