travis:
  secure:
    BINSTAR_TOKEN: MyTZYLpU4ViynIOskwBfFM6I5qFiPUGuLU9XcHQf2p6UmLOz1Osk0Nx2l9cWWuKMddGeMdTCY42k8C9Hr3yaS5gqapSaBJOkz2MZQFlVgCyEy3WM8lfczbvR5g1heaFYXJQn35/iE8o6MKTikIEsVdY6Ggwif4dKj63sEZpZukRC6n+190u8M6d6UNCzn/DCu+4AYc9gTHz+rBrGWDwhK0uj1hRcSqYTSZs1QiqKfAz+HJzMb2lwsLQk4AH/Ixd7WdnZkFExEsnH3B68f1A19l3LlsKbzWiCBz1+BrllMrAGtNjd53HUpZTFog8ePIhPo7leg2N7o+AzYO6mfQA4E+cDmJqD3AUwEV8YBALhzKvI1d7diCH/EOCY82wVFtFTe4VkEvmsPND6HgT9bxYjUpKrFSmbQbfJm8hrmjE2MByY5plILCFX2jA0bh1suW0y+aDdcy/NKtYOJa3lwUUrBoz9zzgD+egsSa4PzHlT6vtQurJr0/0dFNReOWiU/oIIpuguFoSWHY/qycs4NZ2vTMsjneF09KMX9uE6XoGP0K+vFiHPmomZmBf6ckUhkXf4wFWoIeJre0X1mYdsQSOveVBIvffN1tsBe7B/FWFuEXsO7guhVqERANmCwf0pTp5U1z7DX03NWb2dn+HbNXnG/+3758cmlMrYASXIIWqi7Vw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
